config/routes.rb
Rails.application.routes.draw do
  # MVC - Modal, View, Controller
  # Model - represents out database table
  # View - HTML / ERB code
  # Controller - Pulls a Model / Models From Database
  # Sets Instance Variables For Our View

  root 'posts#index'  #Defining what happens when we select specific URLS

  get 'posts/:id', to: 'posts#show', as: 'post_show' #need to reference the id
  get 'post', to: 'posts#new'
  get 'edit_post/:id', to: 'posts#edit', as: 'edit_post'

  post 'posts', to: 'posts#create'

  patch '/post', to: 'posts#update'

  delete 'posts', to: 'posts#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    # GET HTTP VERB
    # get all posts out of the database
    #Active Record way of doing: select * from posts;

    # Views need instance variables to access from the controller
    # .all method always returns array (we always loop through it)
    @posts = Post.all

  end

  def show
    # GET HTTP VERB
    # gets a single post from the database
    @post = Post.find(params[:id])
  end

  def new
    # GET HTTP VERB
    # shows the form to creat a new post
    @post = Post.new
  end

  def create
    # POST HTTP VERB
    # creates a new post record in out database
    @post = Post.new(post_params)
    if @post.save
      # we successfully save a post record
      #redirect_to "/posts/#{@post.id}"
      redirect_to post_show_path(@post)
    else
      # if it fails to save in the database for some reason
      render :new
    end
  end

  def edit
    # GET HTTP VERB
    # shows the same form that new does but prefills it with the posts
    @post = Post.find(params[:id])
    # select * from posts where post.id = params[:id]
  end

    def update
      # PUT / PATCH HTTP VERB
      # updating the post record values
      @post = Post.find(params[:format])
      if @post.update(post_params)
        redirect_to post_show_path(@post)
      else
        render :edit
      end
  end

    def destroy
      # DELETE HTTP VERB
      # deletes a single post record from out database
      @post = Post.find(params[:format])
      @post.destroy
      redirect_to root_path
  end

  private
    def post_params
      params.require(:post).permit(:title, :author, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Posts</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<<h1>
 Editing: <%= @post.title %>
</h1>

 <%= form_for @post do |f| %>
 <%= f.label :title %>
 <%= f.text_field :title %>

<br  />

 <%= f.label :author %>
 <%= f.text_field :author %>

<br />

 <%= f.label :body %>
 <%= f.text_area :body %>

<br />

 <%= f.submit %>
<% end %>

<%= link_to 'Back', post_show_path(@post) %>

app/views/posts/index.html.erb
<h1>All Posts</h1>

<ul>
  <% @posts.each do |post| %>

  <li>
     <%= link_to post.title, post_show_path(post) %> 

   </li>
  <% end %>
</ul>

<%= link_to 'New Post', post_path %>

<!-- <a href='post'>New Post</a> -->

<!-- Echoing ERB Tag -->
<!-- printing out variable values -->
<%= %>

<!-- Non Echoing ERB Tag -->
<!-- looping, conditionals, setting vars -->
<% %>

app/views/posts/new.html.erb
<h1>Create A New Post</h1>

<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
<br />
  <%= f.label :author %>
  <%= f.text_field :author %>
<br />
  <%= f.label :body %>
  <%= f.text_area :body %>
<br />
  <%= f.submit %>
<% end %>

<%= link_to 'All Posts', root_path %>
<!-- <a href='/'>All Posts</a> -->

app/views/posts/show.html.erb
<h1> <%= @post.title %></h1>

<i> Author: <%= @post.author %> </i>
<i> Posted At: <% @post.created_at %> </i>

<p>
  <%= @post.body %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %>
<%= link_to 'Delete', posts_path(@post), method: :delete, data: {confirm: 'Really Delete?'} %>

<%= link_to 'All Posts', root_path %>